nodeLinker: node-modules

npmRegistryServer: "https://registry.npmmirror.com"   #淘宝源

# npmRegistryServer: "https://registry.yarnpkg.com"   #官方源


plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
