version: "3"
services:

  ##
  ## Start Barda (all-in-one)
  ##
  barda-api-service:
    image: bardadev/barda-ce:latest
    container_name: barda
    ports:
      - "3000:3000"
    environment:
      # enable services
      REDIS_ENABLED: "true"
      MONGODB_ENABLED: "true"
      API_SERVICE_ENABLED: "true"
      NODE_SERVICE_ENABLED: "true"
      FRONTEND_ENABLED: "true"
      # generic parameters
      PUID: "1000"
      PGID: "1000"
      # api-service parameters
      #MONGODB_URI: "mongodb://barda:secret123@mongodb/barda?authSource=admin"
      MONGODB_URI: "mongodb://localhost:27017/barda?authSource=admin"
      REDIS_URL: "redis://localhost:6379"
      JS_EXECUTOR_URI: "http://localhost:6060"
      ENABLE_USER_SIGN_UP: "true"
      ENCRYPTION_PASSWORD: "barda.dev"
      ENCRYPTION_SALT: "barda.dev"
      CORS_ALLOWED_DOMAINS: "*"
      # api and node service parameters
      BARDA_API_SERVICE_URL: "http://localhost:8080"
      BARDA_NODE_SERVICE_URL: "http://localhost:6060"
    volumes:
      - ./barda-stacks:/barda-stacks
    restart: unless-stopped

