package com.barda.domain.organization.model;

import static com.barda.infra.util.AssetUtils.toAssetPath;
import static java.util.Optional.ofNullable;
import static org.apache.commons.lang3.ObjectUtils.firstNonNull;

import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Optional;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;
import org.springframework.data.mongodb.core.mapping.Document;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.barda.domain.mongodb.AfterMongodbRead;
import com.barda.domain.mongodb.BeforeMongodbWrite;
import com.barda.domain.mongodb.MongodbInterceptorContext;
import com.barda.sdk.auth.AbstractAuthConfig;
import com.barda.sdk.models.HasIdAndAuditing;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


/**
 * 组织类。
 * 该类表示一个组织，并继承了 HasIdAndAuditing 类，用于提供 ID 和审计功能。
 * 实现了 BeforeMongodbWrite 和 AfterMongodbRead 接口，用于在 MongoDB 写入和读取操作前后执行自定义逻辑。
 */
@Getter
@Setter
@NoArgsConstructor
@Document
public class Organization extends HasIdAndAuditing implements BeforeMongodbWrite, AfterMongodbRead {

    private static final OrganizationCommonSettings EMPTY_SETTINGS = new OrganizationCommonSettings();

    /**
     * 组织名称。
     */
    private String name;

    /**
     * 指示该组织是否为自动生成的。
     */
    private Boolean isAutoGeneratedOrganization;

    /**
     * 联系人姓名。
     */
    private String contactName;

    /**
     * 联系人邮箱。
     */
    private String contactEmail;

    /**
     * 联系人电话号码。
     */
    private String contactPhoneNumber;

    /**
     * 组织徽标的资产 ID。
     * 该 ID 用于在 MongoDB 存储中引用徽标资产。
     */
    @JsonIgnore
    private String logoAssetId;

    /**
     * 获取组织徽标的 URL。
     *
     * @return 徽标的 URL
     */
    public String getLogoUrl() {
        return toAssetPath(logoAssetId);
    }

    /**
     * 指示该组织是否来自第三方登录。
     */
    private String source;

    /**
     * 第三方公司 ID。
     */
    private String thirdPartyCompanyId;

    /**
     * 组织的状态。
     */
    private OrganizationState state;

    /**
     * 组织的域。
     * 该域用于在 MongoDB 存储中引用组织域。
     */
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private OrganizationDomain organizationDomain;

    /**
     * 组织的通用设置。
     */
    private OrganizationCommonSettings commonSettings;

    /**
     * 重写 toString 方法，使用 SHORT_PREFIX_STYLE 格式。
     *
     * @return 对象的字符串表示
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }

    /**
     * 在 MongoDB 读取操作后执行的操作。
     *
     * @param context 包含 MongoDB 拦截器上下文的对象
     */
    @Override
    public void afterMongodbRead(MongodbInterceptorContext context) {
        ofNullable(getOrganizationDomain())
                .ifPresent(domain -> domain.afterMongodbRead(context));
    }

    /**
     * 在 MongoDB 写入操作前执行的操作。
     *
     * @param context 包含 MongoDB 拦截器上下文的对象
     */
    @Override
    public void beforeMongodbWrite(MongodbInterceptorContext context) {
        ofNullable(getOrganizationDomain())
                .ifPresent(domain -> domain.beforeMongodbWrite(context));
    }

    /**
     * 获取组织的通用设置。
     * 如果 commonSettings 为 null，则返回 EMPTY_SETTINGS。
     *
     * @return 组织的通用设置
     */
    public OrganizationCommonSettings getCommonSettings() {
        return firstNonNull(commonSettings, EMPTY_SETTINGS);
    }

    /**
     * 组织的通用设置类。
     * 该类用于在 MongoDB 存储中存储组织的通用设置。
     */
    public static class OrganizationCommonSettings extends HashMap<String, Object> {
        public static final String USER_EXTRA_TRANSFORMER = "userExtraTransformer";
        public static final String USER_EXTRA_TRANSFORMER_UPDATE_TIME = "userExtraTransformer_updateTime";

        // 自定义品牌化配置的键
        public static final String CUSTOM_BRANDING_KEY = "branding";
    }

    /**
     * 获取组织的创建时间。
     *
     * @return 创建时间（以毫秒为单位）
     */
    public long getCreateTime() {
        return createdAt != null ? createdAt.toEpochMilli() : 0;
    }

    /**
     * 获取组织的授权配置列表。
     *
     * @return 授权配置列表
     */
    public List<AbstractAuthConfig> getAuthConfigs() {
        return Optional.ofNullable(organizationDomain)
                .map(OrganizationDomain::getConfigs)
                .orElse(Collections.emptyList());
    }
}
