<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.barda</groupId>
        <artifactId>barda-root</artifactId>
        <version>${revision}</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>barda-plugins</artifactId>
    <name>barda-plugins</name>
    <packaging>pom</packaging>

    <repositories>
        <repository>
            <id>aliyunmaven</id>
            <name>阿里云Maven中央仓库</name>
            <url>https://maven.aliyun.com/repository/central</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>aliyunmaven-public</id>
            <name>阿里云Maven公共仓库</name>
            <url>https://maven.aliyun.com/repository/public</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>aliyunmaven</id>
            <name>阿里云Maven中央仓库</name>
            <url>https://maven.aliyun.com/repository/central</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
        <pluginRepository>
            <id>aliyunmaven-public</id>
            <name>阿里云Maven公共仓库</name>
            <url>https://maven.aliyun.com/repository/public</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>

    <dependencies>
        <dependency>
            <groupId>org.pf4j</groupId>
            <artifactId>pf4j-spring</artifactId>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.barda</groupId>
            <artifactId>barda-sdk</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk7</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>tv.twelvetone.rjson</groupId>
            <artifactId>rjson</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- Test Dependencies -->
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.apache.commons/commons-collections4 -->
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-collections4</artifactId>
        </dependency>

    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.barda</groupId>
                <artifactId>sqlBasedPlugin</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.barda</groupId>
                <artifactId>postgresPlugin</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.barda</groupId>
                <artifactId>restApiPlugin</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.barda</groupId>
                <artifactId>mongoPlugin</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.barda</groupId>
                <artifactId>mysqlPlugin</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.barda</groupId>
                <artifactId>lowcoderApiPlugin</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.barda</groupId>
                <artifactId>elasticSearchPlugin</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.barda</groupId>
                <artifactId>redisPlugin</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.barda</groupId>
                <artifactId>mssqlPlugin</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.barda</groupId>
                <artifactId>smtpPlugin</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.barda</groupId>
                <artifactId>clickHousePlugin</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.barda</groupId>
                <artifactId>googleSheetsPlugin</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.barda</groupId>
                <artifactId>oraclePlugin</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.barda</groupId>
                <artifactId>graphqlPlugin</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.barda</groupId>
                <artifactId>snowflakePlugin</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>testcontainers</artifactId>
                <version>1.19.8</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>


    <modules>
        <module>postgresPlugin</module>
        <module>restApiPlugin</module>
        <module>mongoPlugin</module>
        <module>mysqlPlugin</module>
        <module>bardaApiPlugin</module>
        <module>elasticSearchPlugin</module>
        <module>redisPlugin</module>
        <module>mssqlPlugin</module>
        <module>smtpPlugin</module>
        <module>clickHousePlugin</module>
        <module>googleSheetsPlugin</module>
        <module>oraclePlugin</module>
        <module>graphqlPlugin</module>
        <module>sqlBasedPlugin</module>
        <module>snowflakePlugin</module>
    </modules>
</project>