package com.barda.domain.organization.service;

import static com.barda.domain.authentication.AuthenticationService.DEFAULT_AUTH_CONFIG;
import static com.barda.domain.organization.model.OrganizationState.ACTIVE;
import static com.barda.domain.organization.model.OrganizationState.DELETED;
import static com.barda.domain.util.QueryDslUtils.fieldName;
import static com.barda.sdk.exception.BizError.UNABLE_TO_FIND_VALID_ORG;
import static com.barda.sdk.util.ExceptionUtils.deferredError;
import static com.barda.sdk.util.ExceptionUtils.ofError;
import static com.barda.sdk.util.LocaleUtils.getLocale;
import static com.barda.sdk.util.LocaleUtils.getMessage;

import java.util.Collection;
import java.util.List;
import java.util.Locale;

import javax.annotation.Nonnull;

import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.data.mongodb.core.query.Update;
import org.springframework.http.codec.multipart.Part;
import org.springframework.stereotype.Service;

import com.barda.domain.asset.model.Asset;
import com.barda.domain.asset.service.AssetRepository;
import com.barda.domain.asset.service.AssetService;
import com.barda.domain.group.service.GroupService;
import com.barda.domain.organization.event.OrgDeletedEvent;
import com.barda.domain.organization.model.MemberRole;
import com.barda.domain.organization.model.Organization;
import com.barda.domain.organization.model.Organization.OrganizationCommonSettings;
import com.barda.domain.organization.model.OrganizationDomain;
import com.barda.domain.organization.model.OrganizationState;
import com.barda.domain.organization.model.QOrganization;
import com.barda.domain.organization.repository.OrganizationRepository;
import com.barda.domain.user.model.User;
import com.barda.infra.annotation.PossibleEmptyMono;
import com.barda.infra.mongo.MongoUpsertHelper;
import com.barda.sdk.config.CommonConfig;
import com.barda.sdk.config.dynamic.Conf;
import com.barda.sdk.config.dynamic.ConfigCenter;
import com.barda.sdk.constants.FieldName;
import com.barda.sdk.constants.WorkspaceMode;
import com.barda.sdk.exception.BizError;
import com.barda.sdk.exception.BizException;
import com.barda.sdk.util.UriUtils;

import lombok.extern.slf4j.Slf4j;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

/**
 * 组织服务的实现类。
 * 该类提供创建、查询、更新和删除组织的功能。
 */
@Slf4j
@Service
public class OrganizationServiceImpl implements OrganizationService {

    /**
     * 上传的logo的最大尺寸，单位为KB。
     */
    private final Conf<Integer> logoMaxSizeInKb;

    /**
     * 资产仓库。
     */
    @Autowired
    private AssetRepository assetRepository;

    /**
     * 资产服务。
     */
    @Autowired
    private AssetService assetService;

    /**
     * 组织成员服务。
     */
    @Autowired
    private OrgMemberService orgMemberService;

    /**
     * 用于更新MongoDB的帮助类。
     */
    @Autowired
    private MongoUpsertHelper mongoUpsertHelper;

    /**
     * 组织仓库。
     */
    @Autowired
    private OrganizationRepository repository;

    /**
     * 组服务。
     */
    @Autowired
    private GroupService groupService;

    /**
     * 应用上下文。
     */
    @Autowired
    private ApplicationContext applicationContext;

    /**
     * 通用配置。
     */
    @Autowired
    private CommonConfig commonConfig;

    /**
     * 构造函数，用于注入配置中心。
     */
    @Autowired
    public OrganizationServiceImpl(ConfigCenter configCenter) {
        logoMaxSizeInKb = configCenter.asset().ofInteger("logoMaxSizeInKb", 300);
    }

    /**
     * 创建一个默认的组织。
     *
     * @param user 创建者
     * @return 新创建的组织
     */
    @Override
    public Mono<Organization> createDefault(User user) {
        return Mono.deferContextual(contextView -> {
            Locale locale = getLocale(contextView);
            String userOrgSuffix = getMessage(locale, "USER_ORG_SUFFIX");

            Organization organization = new Organization();
            organization.setName(user.getName() + userOrgSuffix);
            organization.setIsAutoGeneratedOrganization(true);
            // saas mode
            if (commonConfig.getWorkspace().getMode() == WorkspaceMode.SAAS) {
                OrganizationDomain organizationDomain = new OrganizationDomain();
                organizationDomain.setConfigs(List.of(DEFAULT_AUTH_CONFIG));
                organization.setOrganizationDomain(organizationDomain);
                return create(organization, user.getId());
            }
            // enterprise mode
            return joinOrganizationInEnterpriseMode(user.getId())
                    .flatMap(join -> {
                        if (Boolean.TRUE.equals(join)) {
                            return Mono.empty();
                        }
                        OrganizationDomain organizationDomain = new OrganizationDomain();
                        organizationDomain.setConfigs(List.of(DEFAULT_AUTH_CONFIG));
                        organization.setOrganizationDomain(organizationDomain);
                        return create(organization, user.getId());
                    });
        });
    }

    /**
     * 加入企业模式下的组织。
     *
     * @param userId 用户ID
     * @return 是否加入成功
     */
    private Mono<Boolean> joinOrganizationInEnterpriseMode(String userId) {
        return getOrganizationInEnterpriseMode()
                .flatMap(organization -> orgMemberService.addMember(organization.getId(), userId, MemberRole.MEMBER))
                .defaultIfEmpty(false);
    }

    /**
     * 获取企业模式下的组织。
     *
     * @return 企业模式下的组织
     */
    @Override
    @PossibleEmptyMono
    public Mono<Organization> getOrganizationInEnterpriseMode() {
        if (commonConfig.getWorkspace().getMode() == WorkspaceMode.SAAS) {
            return Mono.empty();
        }
        return getByEnterpriseOrgId()
                .switchIfEmpty(repository.findByIsPrimaryOrganizationAndState(true, ACTIVE))
                .switchIfEmpty(repository.findFirstByStateOrderByCreatedAtAsc(ACTIVE));
    }

    /**
     * 获取企业组织ID。
     *
     * @return 企业组织ID
     */
    @Nonnull
    private Mono<Organization> getByEnterpriseOrgId() {
        String enterpriseOrgId = commonConfig.getWorkspace().getEnterpriseOrgId();
        if (StringUtils.isBlank(enterpriseOrgId)) {
            return Mono.empty();
        }
        return repository.findById(enterpriseOrgId)
                .delayUntil(org -> {
                            if (org.getState() == DELETED) {
                                return ofError(BizError.ORG_DELETED_FOR_ENTERPRISE_MODE, "ORG_DELETED_FOR_ENTERPRISE_MODE");
                            }
                            return Mono.empty();
                        }
                );
    }

    /**
     * 创建一个新的组织。
     *
     * @param organization 要创建的组织
     * @param creatorId 创建者ID
     * @return 新创建的组织
     */
    @Override
    public Mono<Organization> create(Organization organization, String creatorId) {

        return Mono.defer(() -> {
                    if (organization == null || StringUtils.isNotBlank(organization.getId())) {
                        return Mono.error(new BizException(BizError.INVALID_PARAMETER, "INVALID_PARAMETER", FieldName.ORGANIZATION));
                    }
                    organization.setState(ACTIVE);
                    return Mono.just(organization);
                })
                .flatMap(org -> repository.count()
                        .map(count -> {
                            if (count == 0 && !org.isPrimary()) {
                                org.setIsPrimaryOrganization(true);
                            }
                            return org;
                        }))
                .flatMap(repository::save)
                .flatMap(newOrg -> onOrgCreated(creatorId, newOrg))
                .log();
    }

    /**
     * 处理组织创建时的操作，包括创建所有用户组、创建开发者组和设置组织管理员。
     *
     * @param userId  创建组织的用户ID
     * @param newOrg  新创建的组织对象
     * @return 创建组织后的 Mono
     */
    private Mono<Organization> onOrgCreated(String userId, Organization newOrg) {
        return groupService.createAllUserGroup(newOrg.getId())
                .then(groupService.createDevGroup(newOrg.getId()))
                .then(setOrgAdmin(userId, newOrg))
                .thenReturn(newOrg);
    }

    /**
     * 设置组织的管理员。
     *
     * @param userId 用户ID
     * @param newOrg 组织
     * @return 是否设置成功
     */
    private Mono<Boolean> setOrgAdmin(String userId, Organization newOrg) {
        return orgMemberService.addMember(newOrg.getId(), userId, MemberRole.ADMIN);
    }

    /**
     * 获取指定ID的组织。
     *
     * @param id 组织ID
     * @return 组织
     */
    @Override
    public Mono<Organization> getById(String id) {
        return repository.findByIdAndState(id, ACTIVE)
                .switchIfEmpty(deferredError(UNABLE_TO_FIND_VALID_ORG, "INVALID_ORG_ID"));
    }

    /**
     * 获取组织的通用设置。
     *
     * @param orgId 组织ID
     * @return 组织的通用设置
     */
    @Override
    public Mono<OrganizationCommonSettings> getOrgCommonSettings(String orgId) {
        return repository.findByIdAndState(orgId, ACTIVE)
                .switchIfEmpty(deferredError(UNABLE_TO_FIND_VALID_ORG, "INVALID_ORG_ID"))
                .map(Organization::getCommonSettings);
    }

    /**
     * 获取指定ID的多个组织。
     *
     * @param ids 组织ID列表
     * @return 组织列表
     */
    @Override
    public Flux<Organization> getByIds(Collection<String> ids) {
        return repository.findByIdInAndState(ids, ACTIVE);
    }

    /**
     * 上传组织的logo。
     *
     * @param organizationId 组织ID
     * @param filePart 上传的文件
     * @return 是否上传成功
     */
    @Override
    public Mono<Boolean> uploadLogo(String organizationId, Part filePart) {

        Mono<Asset> uploadAssetMono = assetService.upload(filePart, logoMaxSizeInKb.get(), false);

        return uploadAssetMono
                .flatMap(uploadedAsset -> {
                    Organization organization = new Organization();
                    final String prevAssetId = organization.getLogoAssetId();
                    organization.setLogoAssetId(uploadedAsset.getId());

                    return mongoUpsertHelper.updateById(organization, organizationId)
                            .flatMap(updateResult -> {
                                if (StringUtils.isEmpty(prevAssetId)) {
                                    return Mono.just(updateResult);
                                }
                                return assetService.remove(prevAssetId).thenReturn(updateResult);
                            });
                });
    }

    /**
     * 删除组织的logo。
     *
     * @param organizationId 组织ID
     * @return 是否删除成功
     */
    @Override
    public Mono<Boolean> deleteLogo(String organizationId) {
        return repository.findByIdAndState(organizationId, ACTIVE)
                .flatMap(organization -> {
                    // delete from asset repo.
                    final String prevAssetId = organization.getLogoAssetId();
                    if (StringUtils.isBlank(prevAssetId)) {
                        return Mono.error(new BizException(BizError.NO_RESOURCE_FOUND, "ASSET_NOT_FOUND", ""));
                    }
                    return assetRepository.findById(prevAssetId)
                            .switchIfEmpty(Mono.error(new BizException(BizError.NO_RESOURCE_FOUND, "ASSET_NOT_FOUND", prevAssetId)))
                            .flatMap(asset -> assetRepository.delete(asset));
                })
                .then(Mono.defer(() -> {
                    // update org.
                    Organization organization = new Organization();
                    organization.setLogoAssetId(null);
                    return mongoUpsertHelper.updateById(organization, organizationId);
                }));
    }

    /**
     * 更新组织。
     *
     * @param orgId 组织ID
     * @param updateOrg 要更新的组织
     * @return 是否更新成功
     */
    @Override
    public Mono<Boolean> update(String orgId, Organization updateOrg) {
        return mongoUpsertHelper.updateById(updateOrg, orgId);
    }

    /**
     * 删除组织。
     *
     * @param orgId 组织ID
     * @return 是否删除成功
     */
    @Override
    public Mono<Boolean> delete(String orgId) {
        Organization organization = new Organization();
        organization.setState(OrganizationState.DELETED);
        return mongoUpsertHelper.updateById(organization, orgId)
                .delayUntil(success -> {
                    if (Boolean.TRUE.equals(success)) {
                        return sendOrgDeletedEvent(orgId);
                    }
                    return Mono.empty();
                });
    }

    /**
     * 发送组织删除事件。
     *
     * @param orgId 要删除的组织的ID
     * @return 发送事件后的 Mono
     */
    private Mono<Void> sendOrgDeletedEvent(String orgId) {
        OrgDeletedEvent event = new OrgDeletedEvent();
        event.setOrgId(orgId);
        applicationContext.publishEvent(event);
        return Mono.empty();
    }

    /**
     * 获取指定来源和第三方公司ID的组织。
     *
     * @param source 来源
     * @param companyId 第三方公司ID
     * @return 组织
     */
    @Override
    public Mono<Organization> getBySourceAndTpCompanyId(String source, String companyId) {
        return repository.findBySourceAndThirdPartyCompanyIdAndState(source, companyId, ACTIVE);
    }

    /**
     * 获取来自referer域的组织。
     *
     * @return 组织
     */
    @Override
    public Mono<Organization> getByDomain() {
        return UriUtils.getRefererDomainFromContext()
                .flatMap(domain -> repository.findByOrganizationDomain_DomainAndState(domain, ACTIVE));
    }

    @Override
    public Mono<Organization> getPrimaryOrganization() {
        return repository.findByIsPrimaryOrganizationAndState(true, ACTIVE);
    }

    /**
     * 更新组织的通用设置。
     *
     * @param orgId 组织ID
     * @param key 键
     * @param value 值
     * @return 是否更新成功
     */
    @Override
    public Mono<Boolean> updateCommonSettings(String orgId, String key, Object value) {
        long updateTime = System.currentTimeMillis();
        Update update = Update.update(fieldName(QOrganization.organization.commonSettings) + "." + key, value)
                .set(fieldName(QOrganization.organization.commonSettings) + "." + buildCommonSettingsUpdateTimeKey(key), updateTime);
        return mongoUpsertHelper.upsert(update, FieldName.ID, orgId, Organization.class);
    }

    /**
     * 构建组织通用设置的更新时间键。
     *
     * @param key 键
     * @return 更新时间键
     */
    private String buildCommonSettingsUpdateTimeKey(String key) {
        return key + "_updateTime";
    }
}
