[program:mongodb]
user=barda
directory=/barda-stacks/data/mongodb
command=mongod --port 27017 --dbpath /barda-stacks/data/mongodb --logpath log --bind_ip %(ENV_MONGO_LISTEN_HOST)s --auth --setParameter authenticationMechanisms=SCRAM-SHA-256,SCRAM-SHA-1
priority=10
autostart=true
autorestart=true
startsecs=10
startretries=3
stdout_logfile=/barda-stacks/logs/%(program_name)s/%(program_name)s.log
redirect_stderr=true
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile_backups=5
stdout_events_enabled=true
stderr_events_enabled=true
