/**
 * Copyright 2021 Appsmith Inc.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * <p>
 */

// copied and adapted for datasource meta structure

package com.barda.sdk.models;

import java.lang.reflect.Type;
import java.util.List;
import java.util.Map;

import javax.annotation.Nonnull;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.google.gson.InstanceCreator;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * 数据源结构类。
 * 包含了数据源的表格、列、键等信息。
 */
@Data
@NoArgsConstructor
public class DatasourceStructure {

    /**
     * 私有的成员变量，表示数据源中的表格列表。
     */
    private List<Table> tables;

    /**
     * 构造函数，创建一个DatasourceStructure实例。
     *
     * @param tables 数据源中的表格列表
     */
    public DatasourceStructure(List<Table> tables) {
        this.tables = tables;
    }

    /**
     * 一个表示表类型的枚举。
     * 它包含了TABLE、VIEW、ALIAS和COLLECTION四个值。
     */
    public enum TableType {

        /**
         * 表示表格类型。
         */
        TABLE,

        /**
         * 表示视图类型。
         */
        VIEW,

        /**
         * 表示别名类型。
         */
        ALIAS,

        /**
         * 表示集合类型。
         */
        COLLECTION,
    }

    /**
     * 表格类。
     * 包含了表格的类型、模式、名称、列、键等信息。
     */
    @Data
    @AllArgsConstructor
    public static class Table {
        private TableType type;         // 表类型
        private String schema;          // 表所属模式
        private String name;            // 表名称
        private List<Column> columns;   // 表的列定义
        private List<Key> keys;         // 表的键定义
        @JsonIgnore
        List<Template> templates;       // 表相关的模板（此处使用 @JsonIgnore 注解表示在序列化/反序列化时忽略该字段）

        /**
         * 添加列到表中
         *
         * @param column 要添加的列对象
         */
        public void addColumn(Column column) {
            this.columns.add(column);
        }

        /**
         * 添加键到表中
         *
         * @param key 要添加的键对象
         */
        public void addKey(Key key) {
            this.keys.add(key);
        }
    }

    /**
     * 列类。
     * 包含了列的名称、类型、默认值、是否是自动生成的等信息。
     */
    @Data
    @AllArgsConstructor
    public static class Column implements Comparable<Column> {
        private String name;
        private String type;
        private String defaultValue;
        private Boolean isAutogenerated;

        @Override
        public int compareTo(@Nonnull Column other) {
            if (other.getName() == null) {
                return 1;
            }

            return name.compareTo(other.getName());
        }
    }

    /**
     * 键接口。
     * 定义了键的通用方法和属性。
     */
    public interface Key extends Comparable<Key> {
        String getType();

        @Override
        default int compareTo(@Nonnull Key other) {
            if (this instanceof PrimaryKey && other instanceof ForeignKey) {
                return -1;
            }
            if (this instanceof ForeignKey && other instanceof PrimaryKey) {
                return 1;
            }
            if (this instanceof final PrimaryKey thisKey && other instanceof final PrimaryKey otherKey) {
                if (thisKey.getName() != null && otherKey.getName() != null) {
                    return thisKey.getName().compareTo(otherKey.getName());
                }
                if (thisKey.getName() == null) {
                    return 1;
                }
                return -1;
            }

            return 0;
        }
    }

    /**
     * 主键类。
     * 继承自 {@link Key}，包含了主键的名称和列名称等信息。
     */
    @Data
    @AllArgsConstructor
    public static class PrimaryKey implements Key {
        private String name;
        private List<String> columnNames;

        public String getType() {
            return "primary key";
        }
    }

    /**
     * 外键类。
     * 继承自 {@link Key}，包含了外键的名称、来自列和去向列等信息。
     */
    @Data
    @AllArgsConstructor
    public static class ForeignKey implements Key {
        private String name;
        private List<String> fromColumns;
        private List<String> toColumns;

        public String getType() {
            return "foreign key";
        }
    }

    /**
     * 模板类。
     * 包含了模板的标题、正文和配置等信息。
     */
    @Data
    @NoArgsConstructor
    public static class Template {
        private String title;
        private String body;
        private Object configuration;

        // 用于为插件创建模板，其中配置存储在 List<Property> 格式

        public Template(String title, String body, List<Property> configuration) {
            this.title = title;
            this.body = body;
            this.configuration = configuration;
        }

        // 用于为插件创建模板，其中配置存储在 Map 格式

        public Template(String title, String body, Map<String, ?> configuration) {
            this.title = title;
            this.body = body;
            this.configuration = configuration;
        }

        // 用于创建不含配置的模板

        public Template(String title, String body) {
            this.title = title;
            this.body = body;
        }
    }

    /**
     * 实例创建者类。
     * 在反序列化时使用 Gson 所需，因为键的实例无法通过无参数构造函数来调用。
     */
    public static class KeyInstanceCreator implements InstanceCreator<Key> {
        @Override
        public Key createInstance(Type type) {
            return () -> null;
        }
    }
}